// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WinterEquipmentRentalApi;

#nullable disable

namespace WinterEquipmentRentalApi.Migrations
{
    [DbContext(typeof(RentDbContext))]
    [Migration("20251224195542_AddedRentalReturnEntity")]
    partial class AddedRentalReturnEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RentalRentalItem", b =>
                {
                    b.Property<string>("RentalItemsId")
                        .HasColumnType("text");

                    b.Property<string>("RentalsId")
                        .HasColumnType("text");

                    b.HasKey("RentalItemsId", "RentalsId");

                    b.HasIndex("RentalsId");

                    b.ToTable("RentalRentalItem");
                });

            modelBuilder.Entity("WinterEquipmentRentalApi.Models.Client", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("WinterEquipmentRentalApi.Models.Rental", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ClientID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PricePerHour")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("RentalDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClientID");

                    b.ToTable("Rentals");
                });

            modelBuilder.Entity("WinterEquipmentRentalApi.Models.RentalItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("RentalItems");
                });

            modelBuilder.Entity("WinterEquipmentRentalApi.Models.RentalReturn", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric");

                    b.Property<string>("RentalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RentalId");

                    b.ToTable("RentalReturns");
                });

            modelBuilder.Entity("RentalRentalItem", b =>
                {
                    b.HasOne("WinterEquipmentRentalApi.Models.RentalItem", null)
                        .WithMany()
                        .HasForeignKey("RentalItemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WinterEquipmentRentalApi.Models.Rental", null)
                        .WithMany()
                        .HasForeignKey("RentalsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WinterEquipmentRentalApi.Models.Rental", b =>
                {
                    b.HasOne("WinterEquipmentRentalApi.Models.Client", "Client")
                        .WithMany("Rentals")
                        .HasForeignKey("ClientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("WinterEquipmentRentalApi.Models.RentalReturn", b =>
                {
                    b.HasOne("WinterEquipmentRentalApi.Models.Rental", "Rental")
                        .WithMany()
                        .HasForeignKey("RentalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rental");
                });

            modelBuilder.Entity("WinterEquipmentRentalApi.Models.Client", b =>
                {
                    b.Navigation("Rentals");
                });
#pragma warning restore 612, 618
        }
    }
}
